"""Flatten every <target>/profile.json into one analysis table for the LLM-performance paper.

  python docs/_export_profiles.py [outdir]      default outdir: papers/lasry

Writes targets.csv (one row per document; target-level fields repeated on each row) and codebook.md
(every column with its description and allowed values, taken from profile.schema.json). Profiles that
fail docs/_check_profile.py are skipped and named on stdout. Lists are joined with '; ', objects are
flattened with dotted names, and "unknown" is kept as written so gaps stay visible in the analysis.
"""
import sys, csv, json, pathlib

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
import _check_profile as cp

def flat(v, prefix, out):
    if isinstance(v, dict):
        for k, x in v.items(): flat(x, f'{prefix}.{k}' if prefix else k, out)
    elif isinstance(v, list):
        if all(not isinstance(x, (dict, list)) for x in v): out[prefix] = '; '.join(str(x) for x in v)
        else: out[prefix] = json.dumps(v, ensure_ascii=False)
    else: out[prefix] = v
    return out

def rows():
    out, skipped = [], []
    for p in sorted(ROOT.glob('*/profile.json')):
        folder = p.parent.name
        if folder in cp.cw.FAMOUS: continue                  # famous targets stay out of the paper data
        if cp.check(folder, quiet=True)[0] != 'valid': skipped.append(folder); continue
        prof = json.loads(p.read_text(encoding='utf-8'))
        base = {'target': folder, 'title': prof['title']}
        for sect in ('system', 'conditions', 'outcome'): flat(prof[sect], sect, base)
        steps = prof['solution'] if isinstance(prof['solution'], list) else []
        base['solution.steps'] = len(steps)
        base['solution.kinds'] = '; '.join(s.get('kind', '') for s in steps if isinstance(s, dict))
        base['solution.failed_steps'] = sum(1 for s in steps if isinstance(s, dict) and s.get('result') in ('failed', 'ruled out'))
        docs = prof['documents']
        base['documents.count'] = len(docs)
        for d in docs: out.append({**base, **flat(d, 'doc', {})})
    return out, skipped

def codebook(cols):
    def find(path):
        s = cp.SCHEMA
        parts = path.split('.')
        if parts[0] == 'doc': s, parts = s['properties']['documents']['items'], parts[1:]
        for k in parts:
            s = s.get('properties', {}).get(k) or (s.get('items', {}).get('properties', {}) or {}).get(k) or {}
        return s
    lines = ['# Codebook for targets.csv', '', 'Generated by docs/_export_profiles.py from profile.schema.json. '
             'Any cell may read "unknown": the field could not be established from the target\'s record.', '',
             '| column | meaning | values |', '|---|---|---|']
    derived = {'target': 'Folder name.', 'solution.steps': 'Number of recorded solution steps.',
               'solution.kinds': 'Kinds of the steps, in order.', 'solution.failed_steps': 'Steps that failed or were ruled out.',
               'documents.count': 'Documents in the target; one CSV row each.'}
    for c in cols:
        s = find(c)
        vals = s.get('enum') or (s.get('items', {}) or {}).get('enum') or ([s['type']] if 'type' in s else [])
        lines.append(f'| {c} | {derived.get(c) or s.get("description", "")} | {", ".join(map(str, vals))} |')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    outdir = ROOT / (sys.argv[1] if len(sys.argv) > 1 else 'papers/lasry')
    outdir.mkdir(parents=True, exist_ok=True)
    data, skipped = rows()
    cols = []
    for r in data:
        for k in r:
            if k not in cols: cols.append(k)
    with open(outdir / 'targets.csv', 'w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for r in data: w.writerow(r)
    (outdir / 'codebook.md').write_text(codebook(cols), encoding='utf-8')
    print(f'{len(data)} document rows from {len({r["target"] for r in data})} profiles -> {outdir.relative_to(ROOT)}/targets.csv, codebook.md')
    if skipped: print('skipped (invalid): ' + ', '.join(skipped))
